### ISSUE TITLE
Aurora Text gradient

### ISSUE THREAD

**Issue by arct0r** [SikandarJODD/svelte-animations#51]
Hey!
First of all awesome work. 

I've been testing Aurora Text in two different projects. The gradients seems to get out of the text. 

<img width="434" alt="Image" src="https://github.com/user-attachments/assets/c52fc568-d65a-4700-b2da-6e25316290c7" />

<img width="510" alt="Image" src="https://github.com/user-attachments/assets/d925c1dc-a3dd-4954-85a8-f5656cb17fbf" />

I just copied the coded provided in the documentation

**Comment by pixelmate-au** [comment]
I have the exactly same issue, it seems related to TW4, but I haven't found a solution for it, hopefully someone can help with it.

**Comment by arct0r** [comment]
> I have the exactly same issue, it seems related to TW4, but I haven't found a solution for it, hopefully someone can help with it.

Not sure about that. I only tested it on <4

**Comment by SikandarJODD** [comment]
Yeep i know this issue @arct0r @pixelmate-au 

try this out : app.css - Tailwind 4 
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --color-1: 0 100% 63%;
    --color-2: 270 100% 63%;
    --color-3: 210 100% 63%;
    --color-4: 195 100% 63%;
    --color-5: 90 100% 63%;
  }

.dark {
    --background: 240 10% 3.9%;
  }
}

@layer base {
  body {
    @apply bg-background ;
  }
}
```
